In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("../data/data.csv")

# Visualização inicial do DataFrame
df.head()

,ID_Pedido,Data_Pedido,Nome_Produto,Categoria,Preco_Unitario,Quantidade,ID_Cliente,Cidade,Estado
0,1000,2026-01-01 22:00:00,Headset 7.1,Acessórios,800.00,5,130,Curitiba,PR
1,1001,2026-01-01 23:00:00,Teclado Mecânico,Acessórios,502.86,7,129,São Paulo,SP
2,1002,2026-01-01 09:00:00,Cadeira Gamer,Móveis,1200.00,6,107,Porto Alegre,RS
3,1003,2026-01-01 07:00:00,Headset 7.1,Acessórios,800.00,5,145,Belo Horizonte,MG
4,1004,2026-01-01 22:00:00,Headset 7.1,Acessórios,800.00,4,106,Rio de Janeiro,RJ

In [7]:
# Visualização final do DataFrame
df.tail()

,ID_Pedido,Data_Pedido,Nome_Produto,Categoria,Preco_Unitario,Quantidade,ID_Cliente,Cidade,Estado
595,1595,2026-04-30 14:00:00,Laptop Gamer,Eletrônicos,7500.00,4,108,Porto Alegre,RS
596,1596,2026-04-30 00:00:00,Headset 7.1,Acessórios,800.00,1,117,Porto Alegre,RS
597,1597,2026-04-30 14:00:00,Teclado Mecânico,Acessórios,506.61,2,116,Fortaleza,CE
598,1598,2026-04-30 11:00:00,Headset 7.1,Acessórios,800.00,3,107,Salvador,BA
599,1599,2026-04-30 16:00:00,Placa de Vídeo,Hardware,4500.00,4,149,Belo Horizonte,MG

In [ ]:
# Quantidade de linhas e colunas (linhas, colunas)
df.shape

(600, 9)

In [ ]:
# Extração de informações gerais do DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       600 non-null    int64
 1   Data_Pedido     600 non-null    str
 2   Nome_Produto    600 non-null    str
 3   Categoria       600 non-null    str
 4   Preco_Unitario  600 non-null    float64
 5   Quantidade      600 non-null    int64
 6   ID_Cliente      600 non-null    int64
 7   Cidade          600 non-null    str
 8   Estado          600 non-null    str
dtypes: float64(1), int64(3), str(5)
memory usage: 42.3 KB

In [9]:
# Resumo estátistico
df.describe()

         ID_Pedido  Preco_Unitario  Quantidade  ID_Cliente
count   600.000000        600.0000  600.000000  600.000000
mean   1299.500000       2262.2358    4.065000  124.876667
std     173.349358       2352.4953    2.045584   14.621369
min    1000.000000        225.3200    1.000000  100.000000
25%    1149.750000        600.0000    2.000000  112.000000
50%    1299.500000        800.0000    4.000000  125.000000
75%    1449.250000       4500.0000    6.000000  138.000000
max    1599.000000       7500.0000    7.000000  149.000000

In [10]:
# Tipos de dados por coluna
df.dtypes

ID_Pedido           int64
Data_Pedido           str
Nome_Produto          str
Categoria             str
Preco_Unitario    float64
Quantidade          int64
ID_Cliente          int64
Cidade                str
Estado                str
dtype: object