In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("../data/data.csv")

In [4]:
# Correção no tipo na coluna 'Data_Pedido' para datetime para análise temporal
df['Data_Pedido'] = pd.to_datetime(df['Data_Pedido'])

# Checagem
df.dtypes

ID_Pedido                  int64
Data_Pedido       datetime64[us]
Nome_Produto                 str
Categoria                    str
Preco_Unitario           float64
Quantidade                 int64
ID_Cliente                 int64
Cidade                       str
Estado                       str
dtype: object

In [ ]:
# Criação de coluna de 'Faturamento' ('Preco_Unitario' x 'Quantidade')
df['Faturamento'] = df['Preco_Unitario'] * df['Quantidade']

# Visualização da nova coluna
df.head()

,ID_Pedido,Data_Pedido,Nome_Produto,Categoria,Preco_Unitario,Quantidade,ID_Cliente,Cidade,Estado,Faturamento
0,1000,2026-01-01 22:00:00,Headset 7.1,Acessórios,800.00,5,130,Curitiba,PR,4000.00
1,1001,2026-01-01 23:00:00,Teclado Mecânico,Acessórios,502.86,7,129,São Paulo,SP,3520.02
2,1002,2026-01-01 09:00:00,Cadeira Gamer,Móveis,1200.00,6,107,Porto Alegre,RS,7200.00
3,1003,2026-01-01 07:00:00,Headset 7.1,Acessórios,800.00,5,145,Belo Horizonte,MG,4000.00
4,1004,2026-01-01 22:00:00,Headset 7.1,Acessórios,800.00,4,106,Rio de Janeiro,RJ,3200.00

In [ ]:
# Criação de coluna 'Tipo_Entrega' para indicar velocidade de entrega com base no Estado
df['Tipo_Entrega'] = df['Estado'].apply(lambda status: 'Rápida' if status in ['SP', 'RJ', 'MG'] else 'Normal')

# Visualização da nova coluna com base no Estado
df[['Estado', 'Tipo_Entrega']].head()

  Estado Tipo_Entrega
0     PR       Normal
1     SP       Rápida
2     RS       Normal
3     MG       Rápida
4     RJ       Rápida

In [12]:
# Informações gerais do DataFrame após tratamento de dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       600 non-null    int64
 1   Data_Pedido     600 non-null    datetime64[us]
 2   Nome_Produto    600 non-null    str
 3   Categoria       600 non-null    str
 4   Preco_Unitario  600 non-null    float64
 5   Quantidade      600 non-null    int64
 6   ID_Cliente      600 non-null    int64
 7   Cidade          600 non-null    str
 8   Estado          600 non-null    str
 9   Faturamento     600 non-null    float64
 10  Tipo_Entrega    600 non-null    str
dtypes: datetime64[us](1), float64(2), int64(3), str(5)
memory usage: 51.7 KB